feat: batch ctfcli requests ~30% reduction in execution time

diff --git a/.github/workflows/containers-azure.yml b/.github/workflows/containers-azure.yml
--- a/.github/workflows/containers-azure.yml
+++ b/.github/workflows/containers-azure.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+    # TODO match on regex instead
     paths:
       - pwn/**
       - web/**
@@ -41,17 +42,10 @@ jobs:
           [challenges]
           EOF
 
-      # azure-identity doesn't support GitHub WIF
-      - uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a # v2
-        with:
-          tenant-id: ${{ vars.AZURE_TENANT_ID }}
-          client-id: ${{ vars.AZURE_CLIENT_ID }}
-          allow-no-subscriptions: true
-
-      - name: Setup Azure Container Registry
-        run: az acr login --name $REGISTRY
-        env:
-          REGISTRY: ${{ vars.REGISTRY }}
+          shopt -s extglob
+          for chal in ?(pwn|web)/*/; do
+            echo "$chal = $chal" >> .ctf/config
+          done
 
       # TODO add buildx support to ctfcli
       # https://github.com/jpribyl/action-docker-layer-caching/issues/38
@@ -63,18 +57,19 @@ jobs:
             docker-layer-cache-
             layer-docker-layer-cache-
 
-      # ignore errors in case a challenge isn't deployable
+      # azure-identity doesn't support GitHub WIF
+      - uses: azure/login@8c334a195cbb38e46038007b304988d888bf676a # v2
+        with:
+          tenant-id: ${{ vars.AZURE_TENANT_ID }}
+          client-id: ${{ vars.AZURE_CLIENT_ID }}
+          allow-no-subscriptions: true
+
+      - name: Setup Azure Container Registry
+        run: az acr login --name ${{ vars.REGISTRY }}
+
+      # TODO raise issue, throws error even if target challenge isn't deployable. ignore all errors for now
       - name: Deploy containers
-        run: |
-          shopt -s extglob
-          for chal in ?(pwn|web)/*/; do
-            ctf challenge deploy $chal --skip-login --host "azure://management.azure.com$AZURE_CONTAINER_ENV?registry=$REGISTRY&identity=$AZURE_CONTAINER_IDENTITY&suffix=$AZURE_CONTAINER_SUFFIX" || true
-          done
-        env:
-          REGISTRY: ${{ vars.REGISTRY }}
-          AZURE_CONTAINER_ENV: ${{ vars.AZURE_CONTAINER_ENV }}
-          AZURE_CONTAINER_IDENTITY: ${{ vars.AZURE_CONTAINER_IDENTITY }}
-          AZURE_CONTAINER_SUFFIX: ${{ vars.AZURE_CONTAINER_SUFFIX }}
+        run: ctf challenge deploy --skip-login --host "azure://management.azure.com${{ vars.AZURE_CONTAINER_ENV }}?registry=${{ vars.REGISTRY }}&identity=${{ vars.AZURE_CONTAINER_IDENTITY }}&suffix=${{ vars.AZURE_CONTAINER_SUFFIX }}" || true
 
       - name: Setup GitHub container registry
         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
diff --git a/.github/workflows/containers-ctfd.yml b/.github/workflows/containers-ctfd.yml
--- a/.github/workflows/containers-ctfd.yml
+++ b/.github/workflows/containers-ctfd.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+    # TODO match on regex instead
     paths:
       - pwn/**
       - web/**
@@ -39,6 +40,11 @@ jobs:
           [challenges]
           EOF
 
+          shopt -s extglob
+          for chal in ?(pwn|web)/*/; do
+            echo "$chal = $chal" >> .ctf/config
+          done
+
       # TODO add buildx support to ctfcli
       # https://github.com/jpribyl/action-docker-layer-caching/issues/38
       - name: Setup Docker cache
@@ -49,13 +55,9 @@ jobs:
             docker-layer-cache-
             layer-docker-layer-cache-
 
-      # ignore errors in case a challenge isn't deployable
+      # TODO raise issue, throws error even if target challenge isn't deployable. ignore all errors for now
       - name: Deploy containers
-        run: |
-          shopt -s extglob
-          for chal in ?(pwn|web)/*/; do
-            ctf challenge deploy $chal || true
-          done
+        run: ctf challenge deploy || true
 
       - name: Setup GitHub container registry
         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
diff --git a/.github/workflows/containers-kubernetes.yml b/.github/workflows/containers-kubernetes.yml
--- a/.github/workflows/containers-kubernetes.yml
+++ b/.github/workflows/containers-kubernetes.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
       - main
+    # TODO match on regex instead
     paths:
       - pwn/**
       - web/**
@@ -30,7 +31,7 @@ jobs:
           curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
           chmod +x kompose
           sudo mv ./kompose /usr/local/bin/kompose
-          echo "$KUBE_CONFIG" > $HOME/.kube/config
+          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
 
           mkdir .ctf
           cat <<EOF > .ctf/config
@@ -43,15 +44,11 @@ jobs:
 
           [challenges]
           EOF
-        env:
-          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
 
-      - name: Setup container registry
-        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
-        with:
-          registry: ${{ vars.REGISTRY}}
-          username: ${{ secrets.REGISTRY_USERNAME }}
-          password: ${{ secrets.REGISTRY_PASSWORD }}
+          shopt -s extglob
+          for chal in ?(pwn|web)/*/; do
+            echo "$chal = $chal" >> .ctf/config
+          done
 
       # TODO add buildx support to ctfcli
       # https://github.com/jpribyl/action-docker-layer-caching/issues/38
@@ -63,15 +60,16 @@ jobs:
             docker-layer-cache-
             layer-docker-layer-cache-
 
-      # ignore errors in case a challenge isn't deployable
+      - name: Setup container registry
+        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
+        with:
+          registry: ${{ vars.REGISTRY}}
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_PASSWORD }}
+
+      # TODO raise issue, throws error even if target challenge isn't deployable. ignore all errors for now
       - name: Deploy containers
-        run: |
-          shopt -s extglob
-          for chal in ?(pwn|web)/*/; do
-            ctf challenge deploy $chal --skip-login --host "kubernetes://KUBE_HOST?registry=$REGISTRY" || true
-          done
-        env:
-          REGISTRY: ${{ vars.REGISTRY }}
+        run: ctf challenge deploy --skip-login --host "kubernetes://${{ vars.KUBE_HOST }}?registry=${{ vars.REGISTRY }}" || true
 
       - name: Setup GitHub container registry
         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
